const genText = document.getElementById("gen-text")
const textEl = document.querySelector(".textMessage")
let currentIndex = 0; // Initialize the index to 0

genText.addEventListener("click", function () {
    let messages = [
        "Hi, Gorgeous!",
        "Happy 7th month of love",
        "I'm glad that you exist",
        "I will treasure you forever",
        "You've been on my mind 24/7",
        "Cheers to more months and years for us",
        "Be true to me & I'll do the same",
        "I miss you 24/7", 
        "Your eyes are too glimmering",
        "I can't imagine a life without you",
        "It's a ride-or-die with you",
        "I want you in my life today, tomorrow, and forever",
        "Those smiles of yours melt me",
        "Always wear your smile, seeing that you look stunning when you wear it",
        "Let me love you until my last breath",
        "You're my first and last",
        "Thank you for being my constant since day 1",
        "Thank you for letting me experience what it feels like to be loved",
        "Every day is worth living, because of you",
        "I only want you for the rest of my life",
        "I want to be with you through your highs and lows.",
        "You're everything I prayed for",
        "I want to be by your side all the time",
        "I wanna hug you tight",
        "I love you, and I will love you forever",
        "My affection for you never fades",
        "Our paths intended to cross",
        "Ikaw ang paborito kong ka-away",
        "Ikaw ang paborito kong asarin",
        "Higit sa lahat...",
        "Ikaw ang paborito kong kausap",
        "I am proud to be yours",
        "I've experienced numerous loves. However, it was always with you!",
        "I am experiencing a day where I realize how lost I would be without you",
        "When we're together, everything is always better",
        "Move in with me and take residence in my heart without any payment🤭",
        "Would you let me keep you forever if I told you I loved you?",
        "May I hear your answer?",
        "I am entirely yours, without a doubt, forever and always",
        "You are flawless from my perspective. You have my undying love",
        "You made me fall in love, so I did",
        "I have a lot of reasons to die, but you are the only reason I have to live",
        "Distance means so little when someone means so much",
        "Every morning is worth waking up for when you and I are in love",
        "You are the reason I understand what love is",
        "You fill my life with joy",
        "You fulfilled all of my dreams",
        "Mind if I ask you this question?",
        "It's uhm...",
        "It's uhm....",
        "It's uhm.....",
        "Do you see me in your future?",
        "Do you see me as your lifetime partner?",
        "Answer those questions before clicking the generate message button",
        "Be my life time partner?",
        "I'll wait for your answer",
        "Is it a YES",
        "or",
        "It's a YES",
        "Sorry, I don't take no for an answer",
        "Just kidding",
        "You can think first",
        "Before saying YES to me",
        "But I would like to hear your sweetest YES",
        "So....",
        "May I know your answer?",
     ]
    
     // Display the current message
    textEl.textContent = messages[currentIndex];

    // Move to the next message (loop back to the beginning if reached the end)
    currentIndex = (currentIndex + 1) % messages.length;
});